---
    deployment:
        tasks:
            - export DEPLOYPATH=/home/7arpy7c7ysm/public_html/
            - /bin/cp -R * $DEPLOYPATH
            - /bin/cp index.html $DEPLOYPATH
            - /bin/cp style.css $DEPLOYPATH