---
    deployment:
        tasks:
            - export DEPLOYPATH=/home/s7arpy7c7ysm/public_html/
            - /bin/cp index.html $DEPLOYPATH
            - /bin/cp style.css $DEPLOYPATH
            - /bin/cp -R inages $DEPLOYPATH