---
    deployment:
        tasks:
            - export DEPLOYPATH=/home/s7arpy7c7ysm/public_html/
            - /bin/cp -R pages $DEPLOYPATH
            - /bin/cp style.css $DEPLOYPATH
            - /bin/cp common.js $DEPLOYPATH
            - /bin/cp -R assets $DEPLOYPATH
            - /bin/cp -R forms $DEPLOYPATH
            - /bin/cp README.md $DEPLOYPATH
            - /bin/cp license.txt $DEPLOYPATH
            - /bin/cp robots.txt $DEPLOYPATH
            - /bin/cp sitemap.txt $DEPLOYPATH